# Generated by Django 5.2.12 on 2026-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('voter_id', models.CharField(max_length=100)),
                ('candidate_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=256)),
            ],
        ),
    ]
