# Generated by Django 5.2.12 on 2026-03-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_block_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='voter_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
