# Generated by Django 5.2.12 on 2026-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_block_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='voter_id',
            field=models.CharField(max_length=100),
        ),
    ]
