# Generated by Django 5.2.12 on 2026-04-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_voters_face_encoding_voters_otp_voters_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
