# Generated by Django 5.2.12 on 2026-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_voters_groups_voters_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
