# Generated by Django 5.2.12 on 2026-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(default='🏛️', help_text='Party symbol emoji (e.g. 🌹, 🌻, ⚡, 🦁)', max_length=10),
        ),
    ]
