# Generated by Django 5.2.12 on 2026-10-08 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='category',
            field=models.CharField(choices=[('college', 'College / University'), ('school', 'School'), ('club', 'Club & Society'), ('local', 'Local Community'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='User who organized this election', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='organization',
            field=models.CharField(blank=True, default='', help_text='School, college, club, or local body name', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election'),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
