# Generated by Django 5.2.12 on 2026-04-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked')], max_length=10)),
                ('reason', models.TextField()),
                ('feat_votes_10m', models.FloatField(default=0)),
                ('feat_votes_1h', models.FloatField(default=0)),
                ('feat_hour_of_day', models.IntegerField(default=0)),
                ('feat_elections_voted', models.IntegerField(default=0)),
                ('feat_global_rate', models.FloatField(default=0)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Log',
                'verbose_name_plural': 'Fraud Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
